"""OnCue constants."""

DOMAIN = "oncue_scheduler"
STORE_KEY = "oncue_scheduler.schedules"
STORE_VERSION = 1
DEFAULT_SLOT_MINUTES = 15
SLOTS_PER_DAY = 96
MAX_CUSTOM_DAYS = 31

CADENCE_DAILY = "daily"
CADENCE_WEEKLY = "weekly"
CADENCE_CUSTOM = "custom"
VALID_CADENCES = {CADENCE_DAILY, CADENCE_WEEKLY, CADENCE_CUSTOM}

SLOT_TYPE_ON_OFF = "on_off"
VALID_SLOT_TYPES = {SLOT_TYPE_ON_OFF}

SIGNAL_SCHEDULES_UPDATED = f"{DOMAIN}_schedules_updated"

DEFAULT_REVERT_DELAY = 180  # seconds (3 minutes)
MAX_REVERT_DELAY = 3600  # 1 hour
